remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin    : "dark" #"default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

locale: "ko_KR"
url: "https://redlasha.github.io"
baseurl: ""
title: redlasha's blog
description: 블로그 준비중
